common:
  save_interval: 50
  test_interval: 1
  log_interval: 1
  max_epoch: 100
  seed: 3401
  amp: False

datasets:
  train_path: '/home/xinyue/code/TCEmodel/Data/train_sample.pkl'
  test_path: '/home/xinyue/code/TCEmodel/Data/seen_test.pkl'
  batch_size: 24
  tensor_cut: 32000
  num_workers: 4
  fixed_length: 0
  pin_memory: True

checkpoint:
  resume: True
  checkpoint_path: '/home/xinyue/code/TCEmodel/stage1/checkpoints_512/bs24_epoch50_lr3e-4.pt'
  disc_checkpoint_path: '/home/xinyue/code/TCEmodel/stage1/checkpoints_512/bs24_epoch50_disc_lr3e-4.pt'
  save_folder: '/home/xinyue/code/TCEmodel/stage1/checkpoints_512'

inference:
  checkpoint_path: ''
  save_folder: '/home/xinyue/code/encodec-pytorch-main/inference'

optimization:
  lr: 3e-4
  disc_lr: 3e-4


lr_scheduler:
  warmup_epoch: 2

model:
  target_bandwidths: 24.
  sample_rate: 16_000
  channels: 1
  train_discriminator: True # you can set it to 2/3 and other number to train discriminator only
  filters: 32
  ratios: [8, 5, 4, 2]
  disc_win_lengths : [256, 512, 1024, 2048]  # 新增256尺度
  disc_hop_lengths : [64, 128, 256, 512]     # 更小的hop_length
  disc_n_ffts : [512, 1024, 2048, 4096]      # 更细粒度分级
  causal: True
  norm: 'weight_norm'
  segment: None
  name: 'my_encodec'
  dimension: 512
  
balancer:
  weights:
    l_t: 0.1
    l_f: 1
    l_g: 3
    l_feat: 3


